config/routes.rb
Rails.application.routes.draw do

  get 'friends/index'
  get 'friends/show'
  get 'friends/new'
  get 'friends/create'
  get 'friends/update'
  get 'friends/destroy'
  resources :profiles do
    resources :certificates
    resources :hobbies
    resources :friends
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/certificate.rb
class Certificate < ApplicationRecord
  belongs_to :profile
  has_one_attached :pdf


end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :profile
end

app/models/hobby.rb
class Hobby < ApplicationRecord
  belongs_to :profile
end

app/models/profile.rb
class Profile < ApplicationRecord
    has_many :hobbies
    has_many :certificates
    has_many :friends
    accepts_nested_attributes_for :hobbies, reject_if: :all_blank
    accepts_nested_attributes_for :certificates, reject_if: :all_blank
    has_one_attached :image



   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
  before_action :set_profile, execept: [:index,:show]

  def index
  end

  def show
  end

  def new
    @cert = @profile.certificates.build
  end

  def create
    @cert = @profile.certificates.build cert_params
    @cert.save
    redirect_to profiles_path
  end
  
  def edit
    @cert = @profile.certificates.find params[:id]
  end

  def update
    @cert = @profile.certificates.find params[:id]
    if @cert.update cert_params 
      redirect_to profiles_path, notice: "cert succesfully updated"
    else
      @cert.update cert_params
      render :edit
    end
  end

  def destroy
    @certificate = @profile.certificates.find params[:id]
    @certificate.destroy
    redirect_to profiles_path
  end

  private
  def set_profile
    @profile = Profile.find params[:profile_id]
  end

  def cert_params 
    params.require(:certificate).permit(:name,:pdf)
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_profile, execept: :index

  def index
  end

  def show
  end

  def new
    @profile = Profile.find params[:profile_id]
    @friend = @profile.friends.build
  end

  def create
    @profile.friends.build friend_params
    if @profile.save
      redirect_to profiles_path
    end
    
  end

  def edit
    @profile = Profile.find params[:profile_id]
    @friends = @profile.friends.find params[:id]
  end

  def update
    @profile = Profile.find params[:profile_id]
    @friends = @profile.friends.find params[:id]
    if @friends.update friend_params
      redirect_to profiles_path
    end
  end


  def destroy
    @profile = Profile.find params[:profile_id]
    @friend = @profile.friends.find params[:id]
    @friend.destroy
    redirect_to profiles_path
  end

  private 
  def set_profile
    @profile = Profile.find params[:profile_id]
  end

  def friend_params
    params.require(:friend).permit(:aka, :url) 
  end 

end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  before_action :set_profile

  def index
  end

  def show
  end

  def new
    @hobbies = @profile.hobbies.build
  end

  def create
    @hobby = @profile.hobbies.build hobby_params
    @hobby.save
    redirect_to profiles_path
  end 

  def edit
    @hobby = @profile.hobbies.find params[:id]
  end

  def update
    @hobbies = @profile.hobbies.find params[:id]
    if @hobbies.update hobby_params
      redirect_to profiles_path
    end
  end

  def destroy
    @hobby = @profile.hobbies.find params[:id]
    @hobby.destroy
    redirect_to profiles_path
  end

  private

  def hobby_params
    params.require(:hobby).permit(:name,:descripticon,:preference,:category) 
  end 

  def set_profile
    @profile = Profile.find params[:profile_id]
  end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, except: [:index, :new, :create]

  def index 
    if @profile_db = Profile.first
       @endpoint = params[:url] 
      if params[:url]
       parser 
      else
        hash_builder
        respond_to do |format|
          format.json { render json: @profile_db }
          format.html 
        end  
      end
    else 
      redirect_to new_profile_path
    end
  end 
  

  def new
    @profile = Profile.new
    @profile.hobbies.new
    @profile.certificates.new
  end 

  def create
    @profile = Profile.new(profile_params)
    @profile.save
    redirect_to @profile, notice: "Customer successfully created"
  end

  def edit 
  end

  def update
    if @profile.update profile_params 
      redirect_to profiles_path
    else 
      render :edit
    end
  end

  def show 
    if @profile
      respond_to do |format|
        format.json { render json: @profile }
        format.html 
      end       
    else
      redirect_to new_profile_path
    end
  end

  def destroy
    @profile.destroy
    redirect_to profiles_path
  end


  private 

  def set_profile
    @profile = Profile.find params[:id]
  end

  def hash_builder 
    @amigos = []
    suma = 0 
    @profile_db.friends.each do |amigo|
      @endpoint = amigo.url
      @amigos[suma] = parser, amigo.url
      suma+=1
    end
    # @certs = []
    # cont = 0 
    # @profile_db.certificates.each do |d|
    #   @certs[cont] = d.name, url_for(d.pdf)
    #   cont+=1
    # end

    @profile = { "profile" => {
      "firstname" => @profile_db.name,
      "lastname" => @profile_db.last_name,
      "subtitle" => @profile_db.subtititle,
      "birthday" => @profile_db.birthday,
      "email" => @profile_db.email,
      "friends" => @amigos,
      "bio" => @profile_db.bio,
      "hobbies" => @profile_db.hobbies,
      "certificates" => @profile_db.certificates,
      "image" => @profile_db.image
    }}
  end

  def parser
    @hash = RestClient.get @endpoint
    @profile = JSON.parse @hash
  end 

  def set_profile 
    @profile = Profile.find params[:id]
  end

  def profile_params
    params.require(:profile).permit(:name, :last_name, :bio, :birthday, :email, :image, :subtititle, :user_name, hobbies_attributes: [:name, :descripticon, :preference, :category], certificates_attributes: [:name,:pdf])
  end 

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/certificates/destroy.html.haml
%h1 Certificates#destroy
%p Find me in app/views/certificates/destroy.html.haml

app/views/certificates/edit.html.haml
.wrapper
  .container
    .row 
      .col-sm-12
        .card.mt-3 
          .card-header
            %h5="Nuevo Certificado" 
          .card-body
            = form_with(model: [@profile, @cert], local: true )  do |friend|
              .row.form-group
                .col-sm-4.col-form-label
                  = friend.label :name
                .col-sm-8  
                  = friend.text_field :name, class: "form-control"
              .row.form-group
                .col-sm-4.col-form-label
                  = friend.label :pdf
                .col-sm-8  
                  = friend.file_field :pdf
              .row.form-group
                .col-sm-6
                  = friend.submit 'Ingresar', class: 'btn btn-primary'  
    

app/views/certificates/index.html.haml
%h1 Certificates#index
%p Find me in app/views/certificates/index.html.haml

app/views/certificates/new.html.haml
.wrapper
  .container
    .row 
      .col-sm-12
        .card.mt-3 
          .card-header
            %h5="Nuevo Certificado" 
          .card-body
            = form_with(model: [:profile, @cert], local: true )  do |friend|
              .row.form-group
                .col-sm-4.col-form-label
                  = friend.label :name
                .col-sm-8  
                  = friend.text_field :name, class: "form-control"
              .row.form-group
                .col-sm-4.col-form-label
                  = friend.label :pdf
                .col-sm-8  
                  = friend.file_field :pdf
              .row.form-group
                .col-sm-6
                  = friend.submit 'Ingresar', class: 'btn btn-primary'  
      

app/views/certificates/show.html.haml
%h1 Certificates#show
%p Find me in app/views/certificates/show.html.haml

app/views/certificates/update.html.haml
%h1 Certificates#update
%p Find me in app/views/certificates/update.html.haml

app/views/friends/create.html.haml
%h1 Friends#create
%p Find me in app/views/friends/create.html.haml

app/views/friends/destroy.html.haml
%h1 Friends#destroy
%p Find me in app/views/friends/destroy.html.haml

app/views/friends/edit.html.haml
.wrapper
  .container
    .row 
      .col-sm-12
        .card.mt-3 
          .card-header
            %h5="Nuevo Amigo" 
          .card-body
            = form_with(model: [@profile, @friends], local: true )  do |friend|
              .row.form-group
                .col-sm-4.col-form-label
                  = friend.label :nickname
                .col-sm-8  
                  = friend.text_field :aka, class: "form-control"
              .row.form-group
                .col-sm-4.col-form-label
                  = friend.label :url
                .col-sm-8  
                  = friend.text_field :url, class: "form-control"
              .row.form-group
                .col-sm-6
                  = friend.submit 'Ingresar', class: 'btn btn-primary'  

app/views/friends/index.html.haml
%h1 Friends#index
%p Find me in app/views/friends/index.html.haml

app/views/friends/new.html.haml
.wrapper
  .container
    .row 
      .col-sm-12
        .card.mt-3 
          .card-header
            %h5="Nuevo Amigo" 
          .card-body
            = form_with(model: [@profile, @friend], local: true )  do |friend|
              .row.form-group
                .col-sm-4.col-form-label
                  = friend.label :nickname
                .col-sm-8  
                  = friend.text_field :aka, class: "form-control"
              .row.form-group
                .col-sm-4.col-form-label
                  = friend.label :url
                .col-sm-8  
                  = friend.text_field :url, class: "form-control"
              .row.form-group
                .col-sm-6
                  = friend.submit 'Ingresar', class: 'btn btn-primary'  
      

  -# .wrapper
  -# .container
  -#   .row 
  -#     .col-sm-12
  -#       .card.mt-3 
  -#         .card-header
  -#           %h5="Nuevo Hobby" 
  -#         .card-body
  -#           = form_with(model: [@profile, @hobby], local: true )do |cert_fields|
  -#             .row.form-group
  -#               .col-sm-4.col-form-label
  -#                 = cert_fields.label :name
  -#               .col-sm-8  
  -#                 = cert_fields.text_field :name, class: "form-control"
  -#             .row.form-group
  -#               .col-sm-4.col-form-label
  -#                 = cert_fields.label :descripticon
  -#               .col-sm-8 
  -#                 = cert_fields.text_field :descripticon, class: "form-control"
  -#             .row.form-group
  -#               .col-sm-4.col-form-label
  -#                 = cert_fields.label :preference
  -#               .col-sm-8 
  -#                 = cert_fields.text_field :preference, class: "form-control"
  -#             .row.form-group
  -#               .col-sm-4.col-form-label
  -#                 = cert_fields.label :category
  -#               .col-sm-8   
  -#                 = cert_fields.text_field :category, class: "form-control"
  -#             .row.form-group
  -#               .col-sm-6
  -#                 = cert_fields.submit 'Ingresar', class: 'btn btn-primary'  

app/views/friends/show.html.haml
%h1 Friends#show
%p Find me in app/views/friends/show.html.haml

app/views/friends/update.html.haml
%h1 Friends#update
%p Find me in app/views/friends/update.html.haml

app/views/hobbies/destroy.html.haml
%h1 Hobbies#destroy
%p Find me in app/views/hobbies/destroy.html.haml

app/views/hobbies/edit.html.haml
.wrapper
  .container
    .row 
      .col-sm-12
        .card.mt-3 
          .card-header
            %h5="Editar Hobby" 
          .card-body
            = form_with(model: [@profile, @hobby], local: true )do |cert_fields|
              .row.form-group
                .col-sm-4.col-form-label
                  = cert_fields.label :name
                .col-sm-8  
                  = cert_fields.text_field :name, class: "form-control"
              .row.form-group
                .col-sm-4.col-form-label
                  = cert_fields.label :descripticon
                .col-sm-8 
                  = cert_fields.text_field :descripticon, class: "form-control"
              .row.form-group
                .col-sm-4.col-form-label
                  = cert_fields.label :preference
                .col-sm-8 
                  = cert_fields.select :preference, [1,2,3,4,5]
              .row.form-group
                .col-sm-4.col-form-label
                  = cert_fields.label :category
                .col-sm-8   
                  = cert_fields.select :category, ["Lectoescritura","Aventura","Fitness","Coleccionismo","Entretenimiento","Construcción","Gastronomía"]
              .row.form-group
                .col-sm-6
                  = cert_fields.submit 'Ingresar', class: 'btn btn-primary'  
  

app/views/hobbies/index.html.haml
%h1 Hobbies#index
%p Find me in app/views/hobbies/index.html.haml

app/views/hobbies/new.html.haml
.wrapper
  .container
    .row 
      .col-sm-12
        .card.mt-3 
          .card-header
            %h5="Nuevo Hobby" 
          .card-body
            = form_with(model: [@profile, @hobbies], local: true )do |cert_fields|
              .row.form-group
                .col-sm-4.col-form-label
                  = cert_fields.label :name
                .col-sm-8  
                  = cert_fields.text_field :name, class: "form-control"
              .row.form-group
                .col-sm-4.col-form-label
                  = cert_fields.label :descripticon
                .col-sm-8 
                  = cert_fields.text_field :descripticon, class: "form-control"
              .row.form-group
                .col-sm-4.col-form-label
                  = cert_fields.label :preference
                .col-sm-8 
                  = cert_fields.select :preference, [1,2,3,4,5]
              .row.form-group
                .col-sm-4.col-form-label
                  = cert_fields.label :category
                .col-sm-8   
                  = cert_fields.select :category, ["Lectoescritura","Aventura","Fitness","Coleccionismo","Entretenimiento","Construcción","Gastronomía"]
              .row.form-group
                .col-sm-6
                  = cert_fields.submit 'Ingresar', class: 'btn btn-primary'  
  

app/views/hobbies/show.html.haml
%h1 Hobbies#show
%p Find me in app/views/hobbies/show.html.haml

app/views/hobbies/update.html.haml
%h1 Hobbies#update
%p Find me in app/views/hobbies/update.html.haml

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title HackProfile
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/profiles/craate.html.haml
%h1 Profiles#craate
%p Find me in app/views/profiles/craate.html.haml

app/views/profiles/destroy.html.haml
%h1 Profiles#destroy
%p Find me in app/views/profiles/destroy.html.haml

app/views/profiles/edit.html.haml
.wrapper
  .container
    .row 
      .col-sm-7
        .card.mt-3 
          .card-header
            %h3 Datos Basicos
          .card-body
            = form_for @profile do |f|
              .row.form-group
                .col-sm-4.col-form-label
                  = f.label :name 
                .col-sm-8  
                  = f.text_field :name, class: "form-control"
              .row.form-group    
                .col-sm-4.col-form-label
                  = f.label :last_name 
                .col-sm-8 
                  = f.text_field :last_name, class: "form-control"
              .row.form-group    
                .col-sm-4.col-form-label
                  = f.label :email
                .col-sm-8
                  = f.email_field :email, class: "form-control"
              .row.form-group    
                .col-sm-4.col-form-label
                  = f.label :biography
                .col-sm-8
                  = f.text_area :bio, class: "form-control", rows: 5
              .row.form-group    
                .col-sm-4.col-form-label
                  = f.label :subtitle
                .col-sm-8
                  = f.text_field :subtititle, class: "form-control"
              .row.form-group    
                .col-sm-4.col-form-label
                  = f.label :username 
                .col-sm-8
                  = f.text_field :user_name, class: "form-control"
              .row.form-group    
                .col-sm-4.col-form-label
                  = f.label :birthday 
                .col-sm-8
                  = f.date_field :birthday, class: "form-control"
              .row.form-group    
                .col-sm-4.col-form-label
                  = f.label :image 
                  = image_tag @profile.image, class: "profile_img_width"
                .col-sm-8
                  = f.file_field :image
              .row.form-group
                .col-sm-6
                  = f.submit 'Ingresar', class: 'btn btn-primary'  
      .col-sm-5
        .col-sm-12          
          .col-sm-12
            .card-mt-3
              .card-body
                %h3 Hobbies
                %table.table
                  %tr
                    %th name
                    %th category 
                    %th test
                  - @profile.hobbies.each do |hobby|
                    %tr
                      %td= hobby.name
                      %td= link_to 'editar', "http://localhost:3000/profiles/#{@profile.id}/hobbies/#{hobby.id}/edit" 
                      %td= link_to 'eliminar', profile_hobby_path(@profile,hobby) , method: :delete, data: { confirm: 'Estas Seguro?' } 
                = link_to 'agregar', "http://localhost:3000/profiles/#{@profile.id}/hobbies/new", class: 'btn btn-primary'
          .col-sm-12
            .card-mt-3
              .card-body
                %h3 Certificados
                %table.table
                  %tr
                    %th name
                    %th category 
                    %th test
                  - @profile.certificates.each do |cert|
                    %tr
                      %td= cert.name
                      %td= link_to 'editar', "http://localhost:3000/profiles/#{@profile.id}/certificates/#{cert.id}/edit" 
                      %td= link_to 'eliminar', profile_certificate_path(@profile,cert) , method: :delete, data: { confirm: 'Estas Seguro?' } 
                = link_to 'agregar', "http://localhost:3000/profiles/#{@profile.id}/certificates/new", class: 'btn btn-primary'
          .col-sm-12
            .card-mt-3
              .card-body
                %h3 Amigos
                %table.table 
                  %tr
                    %th name
                    %th category 
                    %th test
                  - @profile.friends.each do |cert|
                    %tr
                      %td= cert.aka
                      %td= link_to 'editar', "http://localhost:3000/profiles/#{@profile.id}/friends/#{cert.id}/edit" 
                      %td= link_to 'eliminar', profile_friend_path(@profile,cert) , method: :delete, data: { confirm: 'Estas Seguro?' } 
                = link_to 'agregar', "http://localhost:3000/profiles/#{@profile.id}/friends/new", class: 'btn btn-primary'
                  

app/views/profiles/index.html.haml
.wrapper
  .container.mt-4
    .col-md-12
      %h1="#{@profile["profile"]["firstname"]} #{@profile["profile"]["lastname"]}"
    .col-md-12  
      %h2=@profile["profile"]["subtitle"]
    .col-md-12  
      %hr
      %h3.center Información Básica
      %hr
    .col-md-8
      .bio
        %p=@profile["profile"]["bio"]
    .col-md-4
      .profile_image
        = image_tag @profile["profile"]["image"], class: "profile_img_width"
    .col-md-12
      %hr    
      %h3.center Hobbies
      %hr
    .center
      - @profile["profile"]["hobbies"].each do |h|
       
        %span.span_alignment
          %p=h["name"]
          %ul.ul_alignment 
            - h["preference"].to_i.times do |x|
              %li
                = image_tag "star", class: "ul_img_width"
  
        -#http://10.182.99.124:3000/profiles/1.json
    .col-md-12
      %hr
      %h3.center Certificaciones  
      %hr
      %ul.center 
        - if @profile["profile"]["certificates"]
          - @profile["profile"]["certificates"].each do |cert|  
            %li 
              %span= cert["name"]
              - unless params[:url]
                %span= link_to "ver", "#{url_for cert.pdf}"
              
    .col-md-12  
      - unless params[:url]       
        %hr
        %h3.center Contactos
        %hr
    .row
    .col-md-12  
      - unless params[:url]
        - if @profile["profile"]["friends"].size != 0 
          - @profile["profile"]["friends"].each do |friend|
            - if friend[0] == nil
              .col-md-3.offset-md-1-left
                .card.mt-5
                  = image_tag "default.jpg" ,:class => "card-img-top",  width: '50'
                  .card-body
                    .card-title
                      %p= friend["aka"]
                    = link_to "ver perfil", "http://localhost:3000/profiles/?url=#{friend[1]}", class: "btn btn-primary"
            - else 
              = image_tag friend[0]["profile"]["image"] 
              = link_to "ver perfil", "http://localhost:3000/profiles/?url=#{friend[1]}"
        - else
          %p no tienes amigos por los momentos 
    - unless params[:url]
      .col-md-12
        .col-md-1.offset-md-11
          %hr
            = link_to "editar", "http://localhost:3000/profiles/#{1}/edit", class: "btn btn-primary"
          %hr
        
        
          

app/views/profiles/new.html.haml
.wrapper
  .container
    .row 
      .col-12
        .card.mt-3 
          .card-header
            %h3 Datos Basicos
          .card-body
            = form_for @profile do |f|
              .row.form-group
                .col-sm-4.col-form-label
                  = f.label :name 
                .col-sm-8  
                  = f.text_field :name, class: "form-control"
              .row.form-group    
                .col-sm-4.col-form-label
                  = f.label :last_name 
                .col-sm-8 
                  = f.text_field :last_name, class: "form-control"
              .row.form-group    
                .col-sm-4.col-form-label
                  = f.label :email
                .col-sm-8
                  = f.email_field :email, class: "form-control"
              .row.form-group    
                .col-sm-4.col-form-label
                  = f.label :biography
                .col-sm-8
                  = f.text_area :bio, class: "form-control", rows: 5
              .row.form-group    
                .col-sm-4.col-form-label
                  = f.label :subtitle
                .col-sm-8
                  = f.text_field :subtititle, class: "form-control"
              .row.form-group    
                .col-sm-4.col-form-label
                  = f.label :username 
                .col-sm-8
                  = f.text_field :user_name, class: "form-control"
              .row.form-group    
                .col-sm-4.col-form-label
                  = f.label :birthday 
                .col-sm-8
                  = f.date_field :birthday, class: "form-control"
              .row.form-group    
                .col-sm-4.col-form-label
                  = f.label :image 
                .col-sm-8
                  = f.file_field :image
              .row.form-group
                .col-sm-6
                  = f.submit 'Ingresar', class: 'btn btn-primary'  
                  %h2 hobbies (opcional)
              - 1.upto(3) do |x|
                .col-sm-4
                  .card.mt-3 
                    = f.fields_for :hobbies do |hobbie_fields|
                      .field
                        = hobbie_fields.label :name
                        = hobbie_fields.text_field :name, class: "form-control"
                      .field 
                        = hobbie_fields.label :descriticon
                        = hobbie_fields.text_field :descripticon, class: "form-control"
                      .field 
                        = hobbie_fields.label :preference
                        = hobbie_fields.text_field :preference, class: "form-control"
                      .field 
                        = hobbie_fields.label :category
                        = hobbie_fields.text_field :category, class: "form-control"
                %h2 certificados (opcional)
              - 1.upto(3) do |x|
                .hobbie 
                  %h5="certificado #{x}" 
                  = f.fields_for :certificates do |cert_fields|
                    .field
                      = cert_fields.label :name
                      = cert_fields.text_field :name
                    .field
                      = cert_fields.label :pdf
                      = cert_fields.file_field :pdf 
                      
              .actions
                = f.submit
                

app/views/profiles/show.html.haml
%h1="#{@profile.name} #{@profile.last_name}"
%h2=@profile.subtititle
%hr
%h3.center="Informacion Basica"
%hr
.container.center
  .bio
    %p=@profile.bio
    %p=@profile.email
  .profile_image
    = image_tag @profile.image
%hr    
%h3.center Hobbies
%hr
.center
  - @profile.hobbies.each do |h|
    %p=h.name
    %p=h.descripticon
%hr
%h3.center Certificaciones  
%hr
%ul.center 
  - @profile.certificates.each do |cert|
    - if cert.pdf != "nil"
      %li 
        %span= cert.name
        %span= link_to 'ver', "#{url_for cert.pdf}"
%hr
%h3.center Contactos
%hr
%ul.center 
  - @profile.friends.each do |friend|
    = friend.aka
    
      